PROGS=main1 main2
include ../../XX/Makefile.rules


test1a: main1
	@echo "expected result: DDRRRD"
	@time ./main1 ihgpwlah
test1b: main1
	@echo "expected result: DDUDRLRRUDRD"
	@time ./main1 kglvqrro
test1c: main1
	@echo "expected result: DRURDRUDDLLDLUURRDULRLDUUDDDRR"
	@time ./main1 ulqzkmiv
testd: main1
	@echo "expected result: not reachable"
	@time ./main1 hijkl
puzzle1: main1
	@echo "puzzle result:"
	@time ./main1 pxxbnzuo

test2a: main2
	@echo "expected result: 370"
	@time ./main2 ihgpwlah
test2b: main2
	@echo "expected result: 492"
	@time ./main2 kglvqrro
test2c: main2
	@echo "expected result: 830"
	@time ./main2 ulqzkmiv
puzzle2: main2
	@echo "puzzle result:"
	@time ./main2 pxxbnzuo
