PROGS=main1 main2
include ../../XX/Makefile.rules


test1: main1
	@echo "expected: 18f47a30"
	@./main1 abc

puzzle1: main1
	@echo "puzzle result:"
	@./main1 ojvtpuvg


test2: main2
	@echo "expected: 05ace8e3"
	@./main2 abc

puzzle2: main2
	@echo "puzzle result:"
	@./main2 ojvtpuvg


